/**
 * Generates app/lib/searchIndex.ts from the page manifests.
 *
 * The site is a static export, so search runs in the browser. Shipping the full
 * content manifest would be megabytes, so this emits a compact per-route record:
 * title, description and a capped text excerpt.
 */
import fs from "node:fs";
import path from "node:path";
import { pageBlocks } from "../app/lib/pageBlocks";
import { cleanCopy } from "../app/lib/copyFilters";

const APP = path.join(process.cwd(), "app");
const MAX_TEXT = 400;

function routeMeta(slug: string): { title: string; description: string } {
  const file = path.join(APP, slug, "page.tsx");
  if (!fs.existsSync(file)) return { title: "", description: "" };
  const src = fs.readFileSync(file, "utf8");
  const title = /title:\s*"([^"]+)"/.exec(src)?.[1] ?? "";
  const description =
    /description:\s*\n?\s*"([^"]+)"/.exec(src)?.[1] ??
    /description:\s*"([^"]+)"/.exec(src)?.[1] ??
    "";
  return { title, description };
}

/**
 * Enumerate routes from the app directory, not from pageBlocks: pages with no
 * counterpart on the original site have no blocks, and driving the index off
 * blocks alone left them unfindable by search.
 */
const routes = fs
  .readdirSync(APP, { withFileTypes: true })
  .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
  .filter((e) => fs.existsSync(path.join(APP, e.name, "page.tsx")))
  .map((e) => e.name)
  .filter((slug) => slug !== "search")
  .sort();

const entries = routes
  .map((slug) => {
    const blocks = pageBlocks[slug] ?? [];
    const { title, description } = routeMeta(slug);
    const words = blocks.flatMap((b) => [
      b.heading,
      ...cleanCopy(b.paragraphs),
      ...cleanCopy(b.listItems),
    ]);
    const text = cleanCopy(words).join(" ").slice(0, MAX_TEXT);
    return { slug, title: title || slug, description, text };
  })
  .filter((e) => e.title || e.text);

const out = [
  "// AUTO-GENERATED by scripts/build-search-index.ts - do not edit by hand.",
  "",
  "export type SearchDoc = {",
  "  slug: string;",
  "  title: string;",
  "  description: string;",
  "  text: string;",
  "};",
  "",
  "export const searchIndex: SearchDoc[] = [",
  ...entries.map(
    (e) =>
      `  { slug: ${JSON.stringify(e.slug)}, title: ${JSON.stringify(e.title)}, ` +
      `description: ${JSON.stringify(e.description)}, text: ${JSON.stringify(e.text)} },`,
  ),
  "];",
  "",
];

fs.writeFileSync(path.join(APP, "lib", "searchIndex.ts"), out.join("\n"), "utf8");
console.log(`search index: ${entries.length} documents`);
